### ISSUE TITLE
No index.js

### ISSUE THREAD

**Issue by aurantiumCfstBN** [grant/ts2gas#10]
I installed ts2gas with @google/crasp by npm. But it does not work. 

Error: Cannot find module 'ts2gas'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\@google                                                                                                                                                                                               \clasp\src\files.js:44:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

After investigation, I fount ts2gas@1.4.0 did not have "index.js" at local (i.e. at my PC).

So, please include index.js at npm modules.

**Comment by grant** [comment]
I think I forgot to build before publishing. Can you try `ts2gas@1.4.1`?
